@startuml qa-participation-activity-diagram

start
:User accesses Q&A section;

if (Action type?) then (Ask Question)
    :Enter question details;
    :Add tags and context;
    :Submit question;
    :System notifies relevant users;
else (Answer Question)
    :View question details;
    :Write answer;
    :Submit answer;
    if (Is teacher?) then (yes)
        :Option to mark as best answer;
    endif
endif

:Update reputation points;
stop

@enduml